# Building and deploying a Gatsby site via FTP
#
name: Deploy Gatsby site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Restore cache
        uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm install -g @sanity/cli
      - name: Install Sanity dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
        working-directory: studio
      - name: Clean-install Gatsby dependencies
        if: steps.npm-cache.outputs.cache-hit == 'true'
        run: npm ci
      - name: Clean-install Sanity dependencies
        if: steps.npm-cache.outputs.cache-hit == 'true'
        run: npm ci
        working-directory: studio
      - name: Build with Sanity
        uses: sanity-io/github-action-sanity@v0.4
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.REDJACKET_SANITY_DEPLOY }}
        with:
          args: studio deploy
      - name: Build with Gatsby
        env:
          REDJACKET_SANITY_ID: ${{ secrets.REDJACKET_SANITY_ID }}
          REDJACKET_SANITY_DATASET: ${{ secrets.REDJACKET_SANITY_DATASET }}
          REDJACKET_SANITY_TOKEN: ${{ secrets.REDJACKET_SANITY_TOKEN }}
        run: |
          echo SANITY_READ_TOKEN: '${REDJACKET_SANITY_TOKEN}'
          echo SANITY_PROJECT_ID: '${REDJACKET_SANITY_ID}'
          echo SANITY_PROJECT_DATASET: '${REDJACKET_SANITY_DATASET}'
          npm run build

  # Deployment job
  web-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@6647c2f8ad10f869fded8e5a6253c9da11d7fb47
        uses: SamKirkland/FTP-Deploy-Action@3.1.2
        with:
          # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
          ftp-server: ${{ secrets.REDJACKET_FTP_SERVER }}
          # FTP account username
          ftp-username: ${{ secrets.REDJACKET_FTP_USER }}
          # FTP account password
          ftp-password: ${{ secrets.REDJACKET_FTP_PASS }}
          # The local folder to copy, defaults to root project folder
          # optional, default is ./
          local-dir: public/
          server-dir: ./public_html/www/
          # Passes through options into git-ftp
          #git-ftp-args: # optional
